title: Sinapse.dev Software
description: Desenvolvimento de software sob medida para impulsionar o seu negócio. Criamos soluções inovadoras e escaláveis.
author: Sua Empresa
email: contato@sinapse.dev
baseurl: "" # Certifique-se de que esta linha está assim ou não existe
